In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('stock_list_s2006e2021.csv')

In [4]:
df

,id,name,id_name_yrs,s2006e2007bao,s2006e2007bah,s2006e2007bal,s2006e2007yrs,s2006e2008bao,s2006e2008bah,s2006e2008bal,...,s2006e2019bal,s2006e2019yrs,s2006e2020bao,s2006e2020bah,s2006e2020bal,s2006e2020yrs,s2006e2021bao,s2006e2021bah,s2006e2021bal,s2006e2021yrs
0,0050,元大台灣50,0050-元大台灣50-16,15.6,14.7,15.9,2.0,-9.8,-10.3,-8.4,...,7.6,14.0,8.5,8.0,8.9,15.0,8.8,8.4,9.3,16.0
1,0051,元大中型100,0051-元大中型100-16,12.7,11.5,13.0,2.0,-15.8,-16.5,-13.9,...,4.9,14.0,5.7,5.1,6.3,15.0,6.6,6.0,7.2,16.0
2,0052,富邦科技,0052-富邦科技-16,9.0,8.2,9.4,2.0,-15.6,-16.0,-13.7,...,8.3,14.0,10.1,9.6,10.8,15.0,10.3,9.8,11.0,16.0
3,0053,元大電子,0053-元大電子-15,-10.8,-11.0,-9.5,1.0,-32.0,-32.2,-28.9,...,6.4,13.0,7.6,7.0,8.5,14.0,8.1,7.4,8.8,15.0
4,0054,元大台商50,0054-元大台商50-15,-4.1,-4.8,-3.1,1.0,-33.4,-33.7,-30.4,...,3.6,13.0,3.8,3.1,4.6,14.0,4.2,3.7,5.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,9982,NaN,9982-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,9983,NaN,9983-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,9984,NaN,9984-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2620,9985,NaN,9985-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2621,9986,NaN,9986-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
drop_roi_type = ['bao', 'bah']
drop_roi_cl = ['s'+'2006'+'e'+str(ey)+ roit for ey in range(2007, 2022) for roit in drop_roi_type]
drop_roi_cl

['s2006e2007bao',
 's2006e2007bah',
 's2006e2008bao',
 's2006e2008bah',
 's2006e2009bao',
 's2006e2009bah',
 's2006e2010bao',
 's2006e2010bah',
 's2006e2011bao',
 's2006e2011bah',
 's2006e2012bao',
 's2006e2012bah',
 's2006e2013bao',
 's2006e2013bah',
 's2006e2014bao',
 's2006e2014bah',
 's2006e2015bao',
 's2006e2015bah',
 's2006e2016bao',
 's2006e2016bah',
 's2006e2017bao',
 's2006e2017bah',
 's2006e2018bao',
 's2006e2018bah',
 's2006e2019bao',
 's2006e2019bah',
 's2006e2020bao',
 's2006e2020bah',
 's2006e2021bao',
 's2006e2021bah']

In [6]:
df2 = df.drop(drop_roi_cl, axis=1)

In [7]:
df2

,id,name,id_name_yrs,s2006e2007bal,s2006e2007yrs,s2006e2008bal,s2006e2008yrs,s2006e2009bal,s2006e2009yrs,s2006e2010bal,...,s2006e2017bal,s2006e2017yrs,s2006e2018bal,s2006e2018yrs,s2006e2019bal,s2006e2019yrs,s2006e2020bal,s2006e2020yrs,s2006e2021bal,s2006e2021yrs
0,0050,元大台灣50,0050-元大台灣50-16,15.9,2.0,-8.4,3.0,8.3,4.0,9.1,...,7.2,12.0,6.1,13.0,7.6,14.0,8.9,15.0,9.3,16.0
1,0051,元大中型100,0051-元大中型100-16,13.0,2.0,-13.9,3.0,6.6,4.0,8.0,...,4.5,12.0,3.4,13.0,4.9,14.0,6.3,15.0,7.2,16.0
2,0052,富邦科技,0052-富邦科技-16,9.4,2.0,-13.7,3.0,5.0,4.0,5.1,...,6.7,12.0,5.6,13.0,8.3,14.0,10.8,15.0,11.0,16.0
3,0053,元大電子,0053-元大電子-15,-9.5,1.0,-28.9,2.0,2.2,3.0,2.6,...,5.4,11.0,3.9,12.0,6.4,13.0,8.5,14.0,8.8,15.0
4,0054,元大台商50,0054-元大台商50-15,-3.1,1.0,-30.4,2.0,1.7,3.0,3.1,...,3.5,11.0,1.7,12.0,3.6,13.0,4.6,14.0,5.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,9982,NaN,9982-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,9983,NaN,9983-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,9984,NaN,9984-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2620,9985,NaN,9985-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2621,9986,NaN,9986-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
drop_yrs_cl = ['s'+'2006'+'e'+str(ey)+'yrs' for ey in range(2007, 2021)]
drop_yrs_cl

['s2006e2007yrs',
 's2006e2008yrs',
 's2006e2009yrs',
 's2006e2010yrs',
 's2006e2011yrs',
 's2006e2012yrs',
 's2006e2013yrs',
 's2006e2014yrs',
 's2006e2015yrs',
 's2006e2016yrs',
 's2006e2017yrs',
 's2006e2018yrs',
 's2006e2019yrs',
 's2006e2020yrs']

In [9]:
df3 = df2.drop(drop_yrs_cl, axis=1)
df3

,id,name,id_name_yrs,s2006e2007bal,s2006e2008bal,s2006e2009bal,s2006e2010bal,s2006e2011bal,s2006e2012bal,s2006e2013bal,s2006e2014bal,s2006e2015bal,s2006e2016bal,s2006e2017bal,s2006e2018bal,s2006e2019bal,s2006e2020bal,s2006e2021bal,s2006e2021yrs
0,0050,元大台灣50,0050-元大台灣50-16,15.9,-8.4,8.3,9.1,4.3,5.2,5.9,6.8,5.3,6.4,7.2,6.1,7.6,8.9,9.3,16.0
1,0051,元大中型100,0051-元大中型100-16,13.0,-13.9,6.6,8.0,1.9,3.2,4.9,4.6,2.4,2.7,4.5,3.4,4.9,6.3,7.2,16.0
2,0052,富邦科技,0052-富邦科技-16,9.4,-13.7,5.0,5.1,0.7,2.6,3.3,5.7,4.0,5.2,6.7,5.6,8.3,10.8,11.0,16.0
3,0053,元大電子,0053-元大電子-15,-9.5,-28.9,2.2,2.6,-2.5,0.1,1.4,3.8,2.5,3.8,5.4,3.9,6.4,8.5,8.8,15.0
4,0054,元大台商50,0054-元大台商50-15,-3.1,-30.4,1.7,3.1,-1.6,0.5,2.3,2.8,1.6,2.3,3.5,1.7,3.6,4.6,5.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,9982,NaN,9982-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,9983,NaN,9983-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,9984,NaN,9984-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2620,9985,NaN,9985-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2621,9986,NaN,9986-None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df4 = df3[df3.s2006e2021yrs>15]
df4

,id,name,id_name_yrs,s2006e2007bal,s2006e2008bal,s2006e2009bal,s2006e2010bal,s2006e2011bal,s2006e2012bal,s2006e2013bal,s2006e2014bal,s2006e2015bal,s2006e2016bal,s2006e2017bal,s2006e2018bal,s2006e2019bal,s2006e2020bal,s2006e2021bal,s2006e2021yrs
0,0050,元大台灣50,0050-元大台灣50-16,15.9,-8.4,8.3,9.1,4.3,5.2,5.9,6.8,5.3,6.4,7.2,6.1,7.6,8.9,9.3,16.0
1,0051,元大中型100,0051-元大中型100-16,13.0,-13.9,6.6,8.0,1.9,3.2,4.9,4.6,2.4,2.7,4.5,3.4,4.9,6.3,7.2,16.0
2,0052,富邦科技,0052-富邦科技-16,9.4,-13.7,5.0,5.1,0.7,2.6,3.3,5.7,4.0,5.2,6.7,5.6,8.3,10.8,11.0,16.0
242,1101,台泥,1101-台泥-16,47.8,12.3,16.6,13.2,12.7,13.0,14.0,11.9,6.2,8.3,8.1,8.1,10.1,9.9,10.4,16.0
243,1102,亞泥,1102-亞泥-16,75.5,27.3,27.9,21.5,19.5,19.1,17.5,16.0,10.8,9.6,9.4,10.3,12.6,11.3,11.4,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2603,9949,琉園,9949-琉園-16,76.5,5.6,21.6,10.4,8.9,6.2,8.0,5.0,1.2,-1.0,-0.7,-1.8,0.6,0.0,-0.4,16.0
2604,9950,萬國通,9950-萬國通-16,15.0,1.7,17.5,15.3,13.4,13.0,20.2,12.8,10.1,6.9,5.7,5.0,5.6,2.3,3.0,16.0
2605,9951,皇田,9951-皇田-16,48.0,-20.9,18.5,11.3,8.6,15.2,29.7,25.2,27.3,26.0,22.7,13.8,14.0,13.2,12.3,16.0
2609,9960,邁達康,9960-邁達康-16,27.5,-1.6,33.3,23.5,15.1,13.4,13.7,14.2,11.2,18.1,15.2,12.3,12.3,11.1,9.6,16.0
2610,9962,有益,9962-有益-16,10.0,-24.1,8.4,11.5,1.1,4.9,4.9,4.5,-0.8,2.5,2.8,3.9,3.1,3.0,3.9,16.0